### ISSUE TITLE
Can different models be used? 

### ISSUE THREAD

**Issue by Fcucgvhhhvjv** [ZTMIDGO/RWKV-Android#2]
Hi, I want to use another model like redpajam, vicuna, lama, alpca?   The current model is good but can we use rwkv 3b?

**Comment by ZTMIDGO** [comment]
At present, the code only supports RWKV. Currently, due to the size limit of onnx 2gb, larger models cannot be run. However, I will try to use pytorch for Android instead of onnxruntime in the future. However, I am currently doing the porting of rwkv midi, and I have no time to make the Android version of pytorch

**Comment by Fcucgvhhhvjv** [comment]
how can i convert other models? Like i want to try orca mini 3 b. Does it support quantization or is it raw ort
